#-------------------------------
# General Site Settings

title: Software Developer
description: Passionate // Determined // Visionary
email: eliavhyehuda@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Contact, url: '#contact'}


#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Candidate for bachelor of <a href="https://uwaterloo.ca/software-engineering/">Software Engineering</a> at the <a href="https://uwaterloo.ca/">University of Waterloo</a>. Past intern at Edisoft, Genesys, The Ministry of Finance and NexJ Systems. I am very enthusiastic about working and building new projects for a greater purpose. I have experience in mobile and web development.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '8'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '8'}
- {name: Programming, value: '8'}

  
#-------------------------------
# Contact Section
  
social:
- {icon: 'twitter', link: 'https://twitter.com/eliavhyehuda/'}
- {icon: 'github', link: 'https://github.com/eliavhyehuda/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/eliavhyehuda/'}

  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
  
  
  
  
